<?php

namespace Database\Seeders\RoadSpirits;

use App\Enums\CompanionAcquisitionMethod;
use App\Enums\CompanionRole;
use App\Enums\Rarity;
use App\Enums\SkillTarget;
use App\Enums\SkillType;
use App\Models\Companions\Companion;
use App\Models\Creatures\Skill;
use App\Models\Learning\LearningCategory;
use App\Models\Learning\LearningDomain;
use Illuminate\Database\Seeder;

class RoadSpiritsCompanionSeeder extends Seeder
{
    public function run(): void
    {
        $domain = LearningDomain::query()->where('slug', 'driving_license_be')->firstOrFail();
        $categories = LearningCategory::query()
            ->where('learning_domain_id', $domain->id)
            ->get()
            ->keyBy('slug');

        $skills = collect($this->skillDefinitions($categories))
            ->mapWithKeys(function (array $skillData) {
                $skill = Skill::query()->updateOrCreate(
                    ['slug' => $skillData['slug']],
                    array_merge($skillData, [
                        'name_translations' => ['fr' => $skillData['name']],
                        'description_translations' => ['fr' => $skillData['description']],
                        'unlock_level' => $skillData['required_level'],
                        'animation_key' => $this->animationKey($skillData),
                    ]),
                );

                return [$skill->slug => $skill];
            });

        foreach ($this->companionDefinitions() as $companionData) {
            $companion = Companion::query()->updateOrCreate(
                ['slug' => $companionData['slug']],
                [
                    'name' => $companionData['name'],
                    'name_translations' => ['fr' => $companionData['name']],
                    'specialization_category_id' => $categories[$companionData['specialization']]->id,
                    'role' => $companionData['role'],
                    'rarity' => $companionData['rarity'],
                    'base_hp' => $companionData['base_hp'],
                    'base_attack' => $companionData['base_attack'],
                    'base_defense' => $companionData['base_defense'],
                    'base_speed' => $companionData['base_speed'],
                    'description' => $companionData['description'],
                    'description_translations' => ['fr' => $companionData['description']],
                    'unlock_level' => $companionData['unlock_level'],
                    'acquisition_method' => $companionData['acquisition_method'],
                    'sprite_path' => $companionData['sprite_path'],
                    'combat_class' => $companionData['combat_class'],
                    'build_role' => $companionData['build_role'],
                    'specialization_slug' => $companionData['specialization_slug'],
                    'build_tags' => $companionData['build_tags'],
                    'unique_passive_skill_id' => $skills[$companionData['unique_passive_skill']]->id,
                    'signature_skill_id' => $skills[$companionData['signature_skill']]->id,
                ],
            );

            $companion->skills()->sync([
                $skills['attaque-simple']->id => [
                    'unlock_level' => 1,
                    'sort_order' => 1,
                    'is_default' => true,
                ],
                $skills['defense-gardee']->id => [
                    'unlock_level' => 2,
                    'sort_order' => 2,
                    'is_default' => true,
                ],
                $skills['focus']->id => [
                    'unlock_level' => 4,
                    'sort_order' => 3,
                    'is_default' => false,
                ],
                $skills['soin-leger']->id => [
                    'unlock_level' => 6,
                    'sort_order' => 4,
                    'is_default' => false,
                ],
            ]);
        }
    }

    protected function skillDefinitions($categories): array
    {
        return [
            [
                'name' => 'Attaque simple',
                'slug' => 'attaque-simple',
                'description' => 'Une attaque fiable pour ouvrir le duel.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 15,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 1,
                'icon' => 'sword',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.0],
                'tags' => ['physical', 'melee', 'sword'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Garde',
                'slug' => 'defense-gardee',
                'description' => 'Réduit fortement les dégâts du prochain impact.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 6,
                'cooldown' => 2,
                'required_level' => 1,
                'icon' => 'shield',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'self',
                'damage_family' => null,
                'scaling' => ['defense' => 0.6],
                'tags' => ['shield', 'support'],
                'combat_effect' => [
                    'defense_bonus' => 4,
                    'incoming_damage_multiplier' => 0.7,
                    'duration_rounds' => 1,
                ],
            ],
            [
                'name' => 'Focus',
                'slug' => 'focus',
                'description' => 'Prépare une action plus puissante au tour suivant.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 7,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'sparkles',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'self',
                'damage_family' => null,
                'scaling' => ['attack' => 0.4],
                'tags' => ['support', 'control', 'mental'],
                'combat_effect' => [
                    'attack_bonus' => 5,
                    'precision_bonus' => 6,
                    'crit_bonus' => 8,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Soin léger',
                'slug' => 'soin-leger',
                'description' => 'Restaure un peu de vitalité.',
                'type' => SkillType::Heal,
                'target' => SkillTarget::Ally,
                'power' => 20,
                'energy_cost' => 10,
                'cooldown' => 3,
                'required_level' => 3,
                'icon' => 'heart',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 0.7],
                'tags' => ['magical', 'support', 'light', 'ranged'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Signal précoce',
                'slug' => 'signal-precoce',
                'description' => 'Anticipe la bonne option et améliore les ouvertures créées par les compétences de contrôle.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'compass',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['control', 'support', 'mental', 'mark'],
                'specialization_keys' => ['tactician'],
                'role_keys' => ['control', 'hybrid'],
                'combat_effect' => [
                    'precision_bonus' => 4,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.12,
                            'match_skill_tags' => ['control'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Ordre de priorité',
                'slug' => 'ordre-de-priorite',
                'description' => 'Marque un ennemi et l’expose aux attaques coordonnées.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 0,
                'energy_cost' => 9,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'learning_category_id' => $categories['priority']->id,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 0.35],
                'tags' => ['control', 'ranged', 'mental', 'mark'],
                'specialization_keys' => ['tactician'],
                'role_keys' => ['control'],
                'combat_effect' => [
                    'attack_bonus' => -4,
                    'precision_bonus' => -8,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Mire stable',
                'slug' => 'mire-stable',
                'description' => 'Chaque attaque à distance gagne en fiabilité et en létalité.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'ranged', 'bow', 'crit'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'precision_bonus' => 5,
                    'crit_bonus' => 6,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.15,
                            'match_skill_tags' => ['ranged'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Tir d’ouverture',
                'slug' => 'tir-douverture',
                'description' => 'Décoche une salve précise qui prépare l’exécution de la cible.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 19,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'sword',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.05],
                'tags' => ['physical', 'ranged', 'bow', 'mark'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'crit_bonus' => 10,
                ],
            ],
            [
                'name' => 'Course d’avance',
                'slug' => 'course-davance',
                'description' => 'Le premier mouvement du combat ouvre des fenêtres pour tout le groupe.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'control', 'dagger', 'hybrid'],
                'specialization_keys' => ['scout'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'speed_bonus' => 4,
                    'precision_bonus' => 3,
                ],
            ],
            [
                'name' => 'Flanc éclair',
                'slug' => 'flanc-eclair',
                'description' => 'Frappe latérale rapide qui récompense le jeu agressif au corps à corps.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 18,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'sword',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.0, 'speed' => 0.2],
                'tags' => ['physical', 'melee', 'dagger', 'control'],
                'specialization_keys' => ['scout'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'crit_bonus' => 8,
                ],
            ],
            [
                'name' => 'Mur humain',
                'slug' => 'mur-humain',
                'description' => 'La ligne avant tient plus longtemps et protège naturellement les alliés à distance.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'shield',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'melee', 'shield', 'support'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank', 'support'],
                'combat_effect' => [
                    'defense_bonus' => 4,
                    'incoming_damage_multiplier' => 0.92,
                ],
            ],
            [
                'name' => 'Rempart mobile',
                'slug' => 'rempart-mobile',
                'description' => 'Projette une garde sur un allié exposé et stabilise la ligne arrière.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Ally,
                'power' => 0,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'shield',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => null,
                'scaling' => ['defense' => 0.7],
                'tags' => ['physical', 'shield', 'support', 'melee'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank', 'support'],
                'combat_effect' => [
                    'defense_bonus' => 7,
                    'incoming_damage_multiplier' => 0.68,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Lecture froide',
                'slug' => 'lecture-froide',
                'description' => 'Transforme la lecture des risques en pression magique régulière.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'mind',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['magical', 'mental', 'control', 'light'],
                'specialization_keys' => ['analyst'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'magic_attack_bonus' => 5,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.12,
                            'match_skill_tags' => ['magical'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Faille cognitive',
                'slug' => 'faille-cognitive',
                'description' => 'Casse le rythme mental de la cible et ouvre une fenêtre de contrôle.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 0,
                'energy_cost' => 9,
                'cooldown' => 3,
                'required_level' => 2,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'learning_category_id' => $categories['dangers']->id,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 0.45],
                'tags' => ['magical', 'mental', 'control', 'ranged'],
                'specialization_keys' => ['analyst'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'attack_bonus' => -5,
                    'precision_bonus' => -10,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Cadence mixte',
                'slug' => 'cadence-mixte',
                'description' => 'Alterner pression physique et magique rend le kit plus rentable.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'sparkles',
                'rarity' => Rarity::Epic,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['hybrid', 'physical', 'magical', 'energy'],
                'specialization_keys' => ['counter'],
                'role_keys' => ['hybrid'],
                'combat_effect' => [
                    'attack_bonus' => 3,
                    'magic_attack_bonus' => 3,
                ],
            ],
            [
                'name' => 'Onde adaptative',
                'slug' => 'onde-adaptative',
                'description' => 'Libère une pulsation capable de toucher toute la ligne ennemie.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 14,
                'energy_cost' => 14,
                'cooldown' => 3,
                'required_level' => 3,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['attack' => 0.4, 'magic_attack' => 0.8],
                'tags' => ['magical', 'energy', 'ranged', 'hybrid'],
                'specialization_keys' => ['counter'],
                'role_keys' => ['hybrid'],
                'combat_effect' => [],
            ],
        ];
    }

    protected function companionDefinitions(): array
    {
        return [
            [
                'name' => 'Stratège',
                'slug' => 'stratege',
                'sprite_path' => 'companions/character-spritesheet-21.png',
                'specialization' => 'priority',
                'role' => CompanionRole::Dps,
                'rarity' => Rarity::Common,
                'base_hp' => 84,
                'base_attack' => 18,
                'base_defense' => 13,
                'base_speed' => 14,
                'description' => 'Un contrôleur tactique qui ouvre des fenêtres pour le groupe.',
                'unlock_level' => 1,
                'acquisition_method' => CompanionAcquisitionMethod::Starter,
                'combat_class' => 'strategist',
                'build_role' => 'control',
                'specialization_slug' => 'tactician',
                'build_tags' => ['control', 'ranged', 'mental', 'mark'],
                'unique_passive_skill' => 'signal-precoce',
                'signature_skill' => 'ordre-de-priorite',
            ],
            [
                'name' => 'Observateur',
                'slug' => 'observateur',
                'sprite_path' => 'companions/SaraFullSheet.png',
                'specialization' => 'signs',
                'role' => CompanionRole::Precision,
                'rarity' => Rarity::Common,
                'base_hp' => 78,
                'base_attack' => 16,
                'base_defense' => 12,
                'base_speed' => 18,
                'description' => 'DPS distance précis, taillé pour exploiter les cibles marquées.',
                'unlock_level' => 1,
                'acquisition_method' => CompanionAcquisitionMethod::Starter,
                'combat_class' => 'observer',
                'build_role' => 'dps',
                'specialization_slug' => 'shooter',
                'build_tags' => ['physical', 'ranged', 'bow', 'crit'],
                'unique_passive_skill' => 'mire-stable',
                'signature_skill' => 'tir-douverture',
            ],
            [
                'name' => 'Éclaireur',
                'slug' => 'eclaireur',
                'sprite_path' => 'companions/character-spritesheet-21.png',
                'specialization' => 'speed',
                'role' => CompanionRole::Fast,
                'rarity' => Rarity::Common,
                'base_hp' => 76,
                'base_attack' => 17,
                'base_defense' => 11,
                'base_speed' => 21,
                'description' => 'Harcèle, se replace et met la pression au contact.',
                'unlock_level' => 1,
                'acquisition_method' => CompanionAcquisitionMethod::Starter,
                'combat_class' => 'observer',
                'build_role' => 'hybrid',
                'specialization_slug' => 'scout',
                'build_tags' => ['physical', 'melee', 'dagger', 'control'],
                'unique_passive_skill' => 'course-davance',
                'signature_skill' => 'flanc-eclair',
            ],
            [
                'name' => 'Gardien',
                'slug' => 'gardien',
                'sprite_path' => 'companions/SaraFullSheet.png',
                'specialization' => 'safety',
                'role' => CompanionRole::Tank,
                'rarity' => Rarity::Rare,
                'base_hp' => 98,
                'base_attack' => 13,
                'base_defense' => 19,
                'base_speed' => 10,
                'description' => 'Tank frontal qui protège les alliés les plus fragiles.',
                'unlock_level' => 2,
                'acquisition_method' => CompanionAcquisitionMethod::Quest,
                'combat_class' => 'guardian',
                'build_role' => 'tank',
                'specialization_slug' => 'protector',
                'build_tags' => ['physical', 'melee', 'shield', 'support'],
                'unique_passive_skill' => 'mur-humain',
                'signature_skill' => 'rempart-mobile',
            ],
            [
                'name' => 'Analyste',
                'slug' => 'analyste',
                'sprite_path' => 'companions/character-spritesheet-21.png',
                'specialization' => 'dangers',
                'role' => CompanionRole::Support,
                'rarity' => Rarity::Rare,
                'base_hp' => 82,
                'base_attack' => 14,
                'base_defense' => 14,
                'base_speed' => 16,
                'description' => 'Mage de contrôle qui lit le danger et dérègle les plans adverses.',
                'unlock_level' => 3,
                'acquisition_method' => CompanionAcquisitionMethod::Shop,
                'combat_class' => 'strategist',
                'build_role' => 'hybrid',
                'specialization_slug' => 'analyst',
                'build_tags' => ['magical', 'mental', 'control', 'light'],
                'unique_passive_skill' => 'lecture-froide',
                'signature_skill' => 'faille-cognitive',
            ],
            [
                'name' => 'Polyvalent',
                'slug' => 'polyvalent',
                'sprite_path' => 'companions/SaraFullSheet.png',
                'specialization' => 'mixed',
                'role' => CompanionRole::Balanced,
                'rarity' => Rarity::Epic,
                'base_hp' => 88,
                'base_attack' => 16,
                'base_defense' => 16,
                'base_speed' => 16,
                'description' => 'Hybride adaptable, capable de basculer entre soutien, pression et nettoyage.',
                'unlock_level' => 5,
                'acquisition_method' => CompanionAcquisitionMethod::Achievement,
                'combat_class' => 'guardian',
                'build_role' => 'hybrid',
                'specialization_slug' => 'counter',
                'build_tags' => ['hybrid', 'energy', 'physical', 'magical'],
                'unique_passive_skill' => 'cadence-mixte',
                'signature_skill' => 'onde-adaptative',
            ],
        ];
    }

    protected function animationKey(array $skillData): string
    {
        if (($skillData['slot_type'] ?? 'active') === 'passive') {
            return 'idle';
        }

        return match ($skillData['type']) {
            SkillType::Heal, SkillType::Buff, SkillType::ThemeBonus => 'cast',
            SkillType::Shield, SkillType::Defense, SkillType::PenaltyReduction => 'guard',
            SkillType::AreaAttack => 'slash',
            SkillType::Debuff => 'cast',
            default => (($skillData['range_type'] ?? null) === 'ranged' ? 'shoot' : 'attack'),
        };
    }
}
