<?php

namespace Database\Seeders\RoadSpirits;

use App\Enums\Rarity;
use App\Enums\SkillTarget;
use App\Enums\SkillType;
use App\Models\Creatures\Skill;
use App\Models\Learning\LearningCategory;
use App\Models\Learning\LearningDomain;
use App\Models\Skills\SkillNode;
use App\Models\Skills\SkillTree;
use Illuminate\Database\Seeder;

class RoadSpiritsSkillTreeSeeder extends Seeder
{
    public function run(): void
    {
        $domain = LearningDomain::query()->where('slug', 'driving_license_be')->firstOrFail();
        $categories = LearningCategory::query()
            ->where('learning_domain_id', $domain->id)
            ->get()
            ->keyBy('slug');

        $skills = collect($this->skillDefinitions($categories))
            ->mapWithKeys(function (array $skillData) {
                $skill = Skill::query()->updateOrCreate(
                    ['slug' => $skillData['slug']],
                    array_merge($skillData, [
                        'name_translations' => ['fr' => $skillData['name']],
                        'description_translations' => ['fr' => $skillData['description']],
                        'unlock_level' => $skillData['required_level'],
                        'animation_key' => $this->animationKey($skillData),
                    ]),
                );

                return [$skill->slug => $skill];
            });

        SkillTree::query()->whereIn('slug', [
            'hero-road-tactics',
        ])->delete();

        foreach ($this->treeDefinitions() as $treeData) {
            $tree = SkillTree::query()->updateOrCreate(
                ['slug' => $treeData['slug']],
                [
                    'name' => $treeData['name'],
                    'description' => $treeData['description'],
                    'icon' => $treeData['icon'],
                    'subject_type' => $treeData['subject_type'],
                    'subject_key' => $treeData['subject_key'],
                    'class_slug' => $treeData['class_slug'] ?? null,
                    'role_slug' => $treeData['role_slug'] ?? null,
                    'specialization_slug' => $treeData['specialization_slug'] ?? null,
                ],
            );

            $createdNodes = collect($treeData['nodes'])->mapWithKeys(function (array $nodeData) use ($tree, $skills) {
                $node = SkillNode::query()->updateOrCreate(
                    ['slug' => $nodeData['slug']],
                    [
                        'skill_tree_id' => $tree->id,
                        'skill_id' => $skills[$nodeData['skill']]->id,
                        'column_index' => $nodeData['column'],
                        'row_index' => $nodeData['row'],
                        'unlock_cost' => $nodeData['cost'],
                        'special_cost' => $nodeData['special_cost'],
                        'required_level' => $nodeData['required_level'],
                        'sort_order' => ($nodeData['column'] * 10) + $nodeData['row'],
                        'prerequisite_node_ids' => [],
                    ],
                );

                return [$nodeData['slug'] => $node];
            });

            foreach ($treeData['nodes'] as $nodeData) {
                $createdNodes[$nodeData['slug']]->update([
                    'prerequisite_node_ids' => collect($nodeData['prerequisites'])
                        ->map(fn (string $slug): int => (int) $createdNodes[$slug]->id)
                        ->values()
                        ->all(),
                ]);

                $skills[$nodeData['skill']]->update([
                    'prerequisites' => [
                        'node_slugs' => $nodeData['prerequisites'],
                        'required_level' => $nodeData['required_level'],
                    ],
                ]);
            }
        }
    }

    protected function skillDefinitions($categories): array
    {
        return [
            [
                'name' => 'Réflexe Prioritaire',
                'slug' => 'reflexe-prioritaire',
                'description' => 'Les compétences de contrôle prennent plus vite l’ascendant sur les questions de priorité.',
                'type' => SkillType::ThemeBonus,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'compass',
                'rarity' => Rarity::Rare,
                'learning_category_id' => $categories['priority']->id,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['control', 'mental', 'mark'],
                'specialization_keys' => ['tactician'],
                'role_keys' => ['control'],
                'combat_effect' => [
                    'themed_attack_bonus' => 8,
                    'themed_precision_bonus' => 6,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.1,
                            'match_skill_tags' => ['control'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Analyse du Danger',
                'slug' => 'analyse-du-danger',
                'description' => 'Expose la faille d’un ennemi et casse sa précision.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 0,
                'energy_cost' => 10,
                'cooldown' => 3,
                'required_level' => 2,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'learning_category_id' => $categories['dangers']->id,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 0.45],
                'tags' => ['control', 'ranged', 'mental', 'mark'],
                'specialization_keys' => ['tactician', 'analyst'],
                'role_keys' => ['control', 'hybrid'],
                'combat_effect' => [
                    'attack_bonus' => -5,
                    'precision_bonus' => -10,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Lecture Rapide',
                'slug' => 'lecture-rapide',
                'description' => 'Accorde du temps et de la clarté quand le rythme du combat monte.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['support', 'mental', 'light'],
                'specialization_keys' => ['analyst', 'support'],
                'role_keys' => ['support', 'hybrid'],
                'combat_effect' => [
                    'bonus_time_seconds' => 5,
                    'precision_bonus' => 4,
                    'mana_bonus' => 4,
                ],
            ],
            [
                'name' => 'Bouclier de Prudence',
                'slug' => 'bouclier-prudence',
                'description' => 'Fait monter une garde plus dense lorsque le groupe est sous pression.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Ally,
                'power' => 0,
                'energy_cost' => 9,
                'cooldown' => 2,
                'required_level' => 3,
                'icon' => 'shield',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => null,
                'scaling' => ['defense' => 0.8],
                'tags' => ['support', 'shield', 'light', 'ranged'],
                'specialization_keys' => ['support'],
                'role_keys' => ['support', 'tank'],
                'combat_effect' => [
                    'defense_bonus' => 8,
                    'incoming_damage_multiplier' => 0.65,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Gel tactique',
                'slug' => 'gel-tactique',
                'description' => 'Fige mentalement la cible et réduit son impact sur le tour suivant.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 8,
                'energy_cost' => 11,
                'cooldown' => 3,
                'required_level' => 4,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 0.85],
                'tags' => ['magical', 'ice', 'control', 'ranged'],
                'specialization_keys' => ['analyst'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'attack_bonus' => -4,
                    'precision_bonus' => -6,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Concentration',
                'slug' => 'concentration',
                'description' => 'Stabilise la cadence et transforme la réussite en dégâts plus propres.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 4,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['control', 'crit', 'mental'],
                'specialization_keys' => ['tactician', 'analyst'],
                'role_keys' => ['control', 'hybrid'],
                'combat_effect' => [
                    'crit_bonus' => 6,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.15,
                            'match_skill_tags' => ['mental'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Directive Incandescente',
                'slug' => 'directive-incandescente',
                'description' => 'Concentre l’équipe sur une offensive de feu courte mais brutale.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 11,
                'cooldown' => 3,
                'required_level' => 5,
                'icon' => 'sparkles',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'self',
                'damage_family' => null,
                'scaling' => ['magic_attack' => 0.4],
                'tags' => ['magical', 'fire', 'support', 'energy'],
                'specialization_keys' => ['support', 'analyst'],
                'role_keys' => ['support', 'hybrid'],
                'combat_effect' => [
                    'attack_bonus' => 6,
                    'crit_bonus' => 10,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Surcharge Mentale',
                'slug' => 'surcharge-mentale',
                'description' => 'Fait exploser la ligne ennemie sous une onde mentale saturée d’énergie.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 18,
                'energy_cost' => 18,
                'cooldown' => 4,
                'required_level' => 6,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 1.15],
                'tags' => ['magical', 'energy', 'mental', 'control', 'ultimate'],
                'specialization_keys' => ['tactician', 'analyst', 'support'],
                'role_keys' => ['control', 'hybrid', 'support'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Tir guidé',
                'slug' => 'tir-guide',
                'description' => 'Un tir propre qui ouvre la voie aux builds distance.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 18,
                'energy_cost' => 6,
                'cooldown' => 1,
                'required_level' => 2,
                'icon' => 'sword',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.05],
                'tags' => ['physical', 'ranged', 'bow'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Pas de côté',
                'slug' => 'pas-de-cote',
                'description' => 'Le jeu mobile réduit le risque quand le build distance doit respirer.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 2,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'ranged', 'control'],
                'specialization_keys' => ['scout', 'shooter'],
                'role_keys' => ['hybrid', 'dps'],
                'combat_effect' => [
                    'speed_bonus' => 3,
                    'incoming_damage_multiplier' => 0.95,
                ],
            ],
            [
                'name' => 'Poudre aveuglante',
                'slug' => 'poudre-aveuglante',
                'description' => 'Désoriente la cible et fait chuter sa précision.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 0,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 3,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 0.3],
                'tags' => ['physical', 'ranged', 'control', 'poison'],
                'specialization_keys' => ['scout'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'precision_bonus' => -12,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Visée clinique',
                'slug' => 'visee-clinique',
                'description' => 'Les builds critiques à distance montent en puissance.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'ranged', 'crit', 'bow'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'precision_bonus' => 5,
                    'crit_bonus' => 8,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.15,
                            'match_skill_tags' => ['ranged'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Salve ciblée',
                'slug' => 'salve-ciblee',
                'description' => 'Arrose toute la ligne adverse pour user les groupes nombreux.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 12,
                'energy_cost' => 11,
                'cooldown' => 3,
                'required_level' => 4,
                'icon' => 'burst',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 0.9],
                'tags' => ['physical', 'ranged', 'bow'],
                'specialization_keys' => ['shooter'],
                'role_keys' => ['dps'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Lecture des lignes',
                'slug' => 'lecture-des-lignes',
                'description' => 'Les builds distance exploitent mieux les ennemis déjà marqués.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 4,
                'icon' => 'compass',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'ranged', 'mark'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.18,
                            'match_skill_tags' => ['mark'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Exécution marquée',
                'slug' => 'execution-marquee',
                'description' => 'Une frappe de sniper faite pour finir une cible préparée.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 26,
                'energy_cost' => 12,
                'cooldown' => 3,
                'required_level' => 5,
                'icon' => 'sword',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.25],
                'tags' => ['physical', 'ranged', 'bow', 'crit', 'mark'],
                'specialization_keys' => ['sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'crit_bonus' => 12,
                ],
            ],
            [
                'name' => 'Pluie de projectiles',
                'slug' => 'pluie-de-projectiles',
                'description' => 'Ultime distance multi-cible pour les compositions arrière-ligne.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 19,
                'energy_cost' => 18,
                'cooldown' => 4,
                'required_level' => 6,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.2],
                'tags' => ['physical', 'ranged', 'bow', 'ultimate'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Frappe d’ancrage',
                'slug' => 'frappe-dancrage',
                'description' => 'Une base de build mêlée solide, pensée pour tenir la ligne.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 18,
                'energy_cost' => 5,
                'cooldown' => 1,
                'required_level' => 2,
                'icon' => 'sword',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.05],
                'tags' => ['physical', 'melee', 'sword'],
                'specialization_keys' => ['breaker', 'counter'],
                'role_keys' => ['dps', 'hybrid'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Mur de garde',
                'slug' => 'mur-de-garde',
                'description' => 'Pose une garde frontale épaisse pour protéger la rotation du groupe.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 2,
                'icon' => 'shield',
                'rarity' => Rarity::Common,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'self',
                'damage_family' => null,
                'scaling' => ['defense' => 0.9],
                'tags' => ['physical', 'melee', 'shield', 'support'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank', 'support'],
                'combat_effect' => [
                    'defense_bonus' => 9,
                    'incoming_damage_multiplier' => 0.63,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Ténacité de Fer',
                'slug' => 'tenacite-de-fer',
                'description' => 'Les builds tank tiennent mieux les combats longs.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'shield',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'melee', 'shield', 'support'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank'],
                'combat_effect' => [
                    'defense_bonus' => 5,
                    'resistance_bonus' => 4,
                    'hp_multiplier' => 1.1,
                ],
            ],
            [
                'name' => 'Brise-garde',
                'slug' => 'brise-garde',
                'description' => 'Fragilise les défenses adverses pour ouvrir la mêlée.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 10,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 3,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 0.85],
                'tags' => ['physical', 'melee', 'sword', 'control'],
                'specialization_keys' => ['breaker'],
                'role_keys' => ['dps', 'control'],
                'combat_effect' => [
                    'attack_bonus' => -3,
                    'precision_bonus' => -4,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Riposte punie',
                'slug' => 'riposte-punie',
                'description' => 'Les builds critiques mêlée récupèrent plus vite leur rotation.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 4,
                'icon' => 'sword',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'melee', 'counter', 'crit'],
                'specialization_keys' => ['counter'],
                'role_keys' => ['hybrid', 'dps'],
                'combat_effect' => [
                    'crit_bonus' => 6,
                    'modifiers' => [
                        [
                            'stat' => 'cooldown_refund_on_crit',
                            'mode' => 'add',
                            'value' => 1,
                            'match_skill_tags' => ['melee'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Ancrage lourd',
                'slug' => 'ancrage-lourd',
                'description' => 'Ralentit l’hémorragie de dégâts quand la ligne avant encaisse tout.',
                'type' => SkillType::PenaltyReduction,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 4,
                'icon' => 'mind',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'melee', 'shield', 'support'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank', 'support'],
                'combat_effect' => [
                    'incoming_damage_multiplier' => 0.88,
                    'penalty_reduction' => 25,
                ],
            ],
            [
                'name' => 'Charge-bastion',
                'slug' => 'charge-bastion',
                'description' => 'Percute toute la première ligne et impose un vrai style frontline.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 15,
                'energy_cost' => 12,
                'cooldown' => 3,
                'required_level' => 5,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.0, 'defense' => 0.2],
                'tags' => ['physical', 'melee', 'shield'],
                'specialization_keys' => ['protector', 'breaker'],
                'role_keys' => ['tank', 'dps'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Verdict du Rempart',
                'slug' => 'verdict-du-rempart',
                'description' => 'Ultime de mêlée pensé pour les builds tank, breaker et counter.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 30,
                'energy_cost' => 18,
                'cooldown' => 4,
                'required_level' => 6,
                'icon' => 'sword',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.35, 'defense' => 0.25],
                'tags' => ['physical', 'melee', 'sword', 'ultimate'],
                'specialization_keys' => ['protector', 'breaker', 'counter'],
                'role_keys' => ['tank', 'dps', 'hybrid'],
                'combat_effect' => [
                    'crit_bonus' => 10,
                ],
            ],
            [
                'name' => 'Fenêtre d’ordre',
                'slug' => 'fenetre-dordre',
                'description' => 'Le prochain enchaînement de contrôle devient plus tranchant.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 8,
                'cooldown' => 2,
                'required_level' => 3,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'self',
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['control', 'mental', 'support'],
                'specialization_keys' => ['tactician'],
                'role_keys' => ['control'],
                'combat_effect' => [
                    'attack_bonus' => 4,
                    'precision_bonus' => 8,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Plan Décisionnel',
                'slug' => 'plan-decisionnel',
                'description' => 'Déploie un plan de zone qui punit toute la ligne ennemie.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 16,
                'energy_cost' => 15,
                'cooldown' => 4,
                'required_level' => 5,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 1.0],
                'tags' => ['control', 'mental', 'energy', 'ultimate'],
                'specialization_keys' => ['tactician'],
                'role_keys' => ['control'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Percée balistique',
                'slug' => 'percee-balistique',
                'description' => 'Amplifie les dégâts sur cibles déjà préparées.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'target',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'ranged', 'mark'],
                'specialization_keys' => ['shooter'],
                'role_keys' => ['dps'],
                'combat_effect' => [
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.18,
                            'match_skill_tags' => ['mark'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Salve d’interception',
                'slug' => 'salve-dinterception',
                'description' => 'Nettoie la ligne arrière adverse avant qu’elle ne s’installe.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 17,
                'energy_cost' => 16,
                'cooldown' => 4,
                'required_level' => 5,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.1],
                'tags' => ['physical', 'ranged', 'bow', 'ultimate'],
                'specialization_keys' => ['shooter', 'sniper'],
                'role_keys' => ['dps'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Piste chaude',
                'slug' => 'piste-chaude',
                'description' => 'Les critiques au corps à corps remettent plus vite l’éclaireur en action.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'sparkles',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['physical', 'melee', 'dagger', 'crit'],
                'specialization_keys' => ['scout'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'crit_bonus' => 6,
                    'modifiers' => [
                        [
                            'stat' => 'cooldown_refund_on_crit',
                            'mode' => 'add',
                            'value' => 1,
                            'match_skill_tags' => ['melee'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Coupure de trajectoire',
                'slug' => 'coupure-de-trajectoire',
                'description' => 'Coupe l’élan ennemi et garde le contrôle de la mêlée.',
                'type' => SkillType::Debuff,
                'target' => SkillTarget::Enemy,
                'power' => 14,
                'energy_cost' => 9,
                'cooldown' => 3,
                'required_level' => 5,
                'icon' => 'target',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'active',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 1.0],
                'tags' => ['physical', 'melee', 'dagger', 'control'],
                'specialization_keys' => ['scout'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'attack_bonus' => -4,
                    'precision_bonus' => -8,
                    'duration_rounds' => 2,
                ],
            ],
            [
                'name' => 'Garde partagée',
                'slug' => 'garde-partagee',
                'description' => 'Chaque bouclier rend de l’énergie et entretient la rotation défensive.',
                'type' => SkillType::Shield,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'shield',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['shield', 'support', 'melee'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank', 'support'],
                'combat_effect' => [
                    'modifiers' => [
                        [
                            'stat' => 'resource_on_shield',
                            'mode' => 'add',
                            'value' => 4,
                            'match_skill_tags' => ['shield'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Bastion tournant',
                'slug' => 'bastion-tournant',
                'description' => 'Balaye toute la ligne ennemie tout en maintenant la front-line stable.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 16,
                'energy_cost' => 15,
                'cooldown' => 4,
                'required_level' => 5,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'physical',
                'scaling' => ['attack' => 0.95, 'defense' => 0.25],
                'tags' => ['physical', 'melee', 'shield', 'ultimate'],
                'specialization_keys' => ['protector'],
                'role_keys' => ['tank'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Cartographie du risque',
                'slug' => 'cartographie-du-risque',
                'description' => 'Convertit la lecture du danger en précision magique continue.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 3,
                'icon' => 'mind',
                'rarity' => Rarity::Rare,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['magical', 'control', 'mental', 'light'],
                'specialization_keys' => ['analyst'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [
                    'precision_bonus' => 5,
                    'magic_attack_bonus' => 4,
                    'modifiers' => [
                        [
                            'stat' => 'damage_multiplier',
                            'mode' => 'multiply',
                            'value' => 1.14,
                            'match_skill_tags' => ['control'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Onde de clarté',
                'slug' => 'onde-de-clarte',
                'description' => 'Projette une onde de lumière qui nettoie toute la ligne ennemie.',
                'type' => SkillType::AreaAttack,
                'target' => SkillTarget::AllEnemies,
                'power' => 17,
                'energy_cost' => 16,
                'cooldown' => 4,
                'required_level' => 5,
                'icon' => 'burst',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'ranged',
                'damage_family' => 'magical',
                'scaling' => ['magic_attack' => 1.05],
                'tags' => ['magical', 'light', 'control', 'ultimate'],
                'specialization_keys' => ['analyst'],
                'role_keys' => ['hybrid', 'control'],
                'combat_effect' => [],
            ],
            [
                'name' => 'Surcadence',
                'slug' => 'surcadence',
                'description' => 'Le build hybride récupère plus vite son cycle sur critique.',
                'type' => SkillType::Buff,
                'target' => SkillTarget::Self,
                'power' => 0,
                'energy_cost' => 0,
                'cooldown' => 0,
                'required_level' => 4,
                'icon' => 'sparkles',
                'rarity' => Rarity::Epic,
                'is_passive' => true,
                'slot_type' => 'passive',
                'resource_type' => 'energy',
                'range_type' => null,
                'damage_family' => null,
                'scaling' => [],
                'tags' => ['hybrid', 'crit', 'energy'],
                'specialization_keys' => ['counter'],
                'role_keys' => ['hybrid'],
                'combat_effect' => [
                    'crit_bonus' => 5,
                    'modifiers' => [
                        [
                            'stat' => 'cooldown_refund_on_crit',
                            'mode' => 'add',
                            'value' => 1,
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Rupture adaptative',
                'slug' => 'rupture-adaptative',
                'description' => 'Ultime hybride qui convertit attaque et puissance magique dans la même frappe.',
                'type' => SkillType::Attack,
                'target' => SkillTarget::Enemy,
                'power' => 28,
                'energy_cost' => 18,
                'cooldown' => 4,
                'required_level' => 6,
                'icon' => 'sword',
                'rarity' => Rarity::Epic,
                'is_passive' => false,
                'slot_type' => 'ultimate',
                'resource_type' => 'energy',
                'range_type' => 'melee',
                'damage_family' => 'magical',
                'scaling' => ['attack' => 0.65, 'magic_attack' => 0.85],
                'tags' => ['hybrid', 'magical', 'physical', 'energy', 'ultimate'],
                'specialization_keys' => ['counter'],
                'role_keys' => ['hybrid'],
                'combat_effect' => [
                    'crit_bonus' => 8,
                ],
            ],
        ];
    }

    protected function treeDefinitions(): array
    {
        return [
            [
                'slug' => 'hero-strategist-doctrine',
                'name' => 'Doctrine du Stratège',
                'description' => 'Branches tactiques orientées contrôle, support et magie d’analyse.',
                'icon' => 'compass',
                'subject_type' => 'hero',
                'subject_key' => 'hero',
                'class_slug' => 'strategist',
                'role_slug' => 'hybrid',
                'nodes' => [
                    ['slug' => 'hero-reflexe-prioritaire', 'skill' => 'reflexe-prioritaire', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-analyse-danger', 'skill' => 'analyse-du-danger', 'column' => 1, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-lecture-rapide', 'skill' => 'lecture-rapide', 'column' => 2, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-reflexe-prioritaire']],
                    ['slug' => 'hero-bouclier-prudence', 'skill' => 'bouclier-prudence', 'column' => 2, 'row' => 3, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-analyse-danger']],
                    ['slug' => 'hero-gel-tactique', 'skill' => 'gel-tactique', 'column' => 3, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-lecture-rapide']],
                    ['slug' => 'hero-concentration', 'skill' => 'concentration', 'column' => 3, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-reflexe-prioritaire', 'hero-analyse-danger']],
                    ['slug' => 'hero-directive-incandescente', 'skill' => 'directive-incandescente', 'column' => 3, 'row' => 3, 'cost' => 1, 'special_cost' => 0, 'required_level' => 5, 'prerequisites' => ['hero-bouclier-prudence']],
                    ['slug' => 'hero-surcharge-mentale', 'skill' => 'surcharge-mentale', 'column' => 4, 'row' => 2, 'cost' => 2, 'special_cost' => 1, 'required_level' => 6, 'prerequisites' => ['hero-gel-tactique', 'hero-concentration', 'hero-directive-incandescente']],
                ],
            ],
            [
                'slug' => 'hero-observer-ballistics',
                'name' => 'Ballistique de l’Observateur',
                'description' => 'Branches distance, critique et harcèlement de précision.',
                'icon' => 'target',
                'subject_type' => 'hero',
                'subject_key' => 'hero',
                'class_slug' => 'observer',
                'role_slug' => 'dps',
                'nodes' => [
                    ['slug' => 'hero-tir-guide', 'skill' => 'tir-guide', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-pas-de-cote', 'skill' => 'pas-de-cote', 'column' => 1, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-poudre-aveuglante', 'skill' => 'poudre-aveuglante', 'column' => 2, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-pas-de-cote']],
                    ['slug' => 'hero-visee-clinique', 'skill' => 'visee-clinique', 'column' => 2, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-tir-guide']],
                    ['slug' => 'hero-salve-ciblee', 'skill' => 'salve-ciblee', 'column' => 3, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-visee-clinique']],
                    ['slug' => 'hero-lecture-des-lignes', 'skill' => 'lecture-des-lignes', 'column' => 3, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-poudre-aveuglante', 'hero-visee-clinique']],
                    ['slug' => 'hero-execution-marquee', 'skill' => 'execution-marquee', 'column' => 4, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 5, 'prerequisites' => ['hero-lecture-des-lignes']],
                    ['slug' => 'hero-pluie-de-projectiles', 'skill' => 'pluie-de-projectiles', 'column' => 4, 'row' => 2, 'cost' => 2, 'special_cost' => 1, 'required_level' => 6, 'prerequisites' => ['hero-salve-ciblee', 'hero-execution-marquee']],
                ],
            ],
            [
                'slug' => 'hero-guardian-vanguard',
                'name' => 'Avant-garde du Gardien',
                'description' => 'Branches tank, breaker et contre-attaque pour les builds de première ligne.',
                'icon' => 'shield',
                'subject_type' => 'hero',
                'subject_key' => 'hero',
                'class_slug' => 'guardian',
                'role_slug' => 'tank',
                'nodes' => [
                    ['slug' => 'hero-frappe-dancrage', 'skill' => 'frappe-dancrage', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-mur-de-garde', 'skill' => 'mur-de-garde', 'column' => 1, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 2, 'prerequisites' => []],
                    ['slug' => 'hero-tenacite-de-fer', 'skill' => 'tenacite-de-fer', 'column' => 2, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-mur-de-garde']],
                    ['slug' => 'hero-brise-garde', 'skill' => 'brise-garde', 'column' => 2, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => ['hero-frappe-dancrage']],
                    ['slug' => 'hero-riposte-punie', 'skill' => 'riposte-punie', 'column' => 3, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-brise-garde']],
                    ['slug' => 'hero-ancrage-lourd', 'skill' => 'ancrage-lourd', 'column' => 3, 'row' => 2, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => ['hero-tenacite-de-fer']],
                    ['slug' => 'hero-charge-bastion', 'skill' => 'charge-bastion', 'column' => 4, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 5, 'prerequisites' => ['hero-brise-garde', 'hero-tenacite-de-fer']],
                    ['slug' => 'hero-verdict-du-rempart', 'skill' => 'verdict-du-rempart', 'column' => 4, 'row' => 2, 'cost' => 2, 'special_cost' => 1, 'required_level' => 6, 'prerequisites' => ['hero-riposte-punie', 'hero-ancrage-lourd', 'hero-charge-bastion']],
                ],
            ],
            [
                'slug' => 'companion-stratege-command',
                'name' => 'Commandements du Stratège',
                'description' => 'Renforce le contrôle et la coordination de l’allié tactique.',
                'icon' => 'compass',
                'subject_type' => 'companion',
                'subject_key' => 'stratege',
                'class_slug' => 'strategist',
                'role_slug' => 'control',
                'specialization_slug' => 'tactician',
                'nodes' => [
                    ['slug' => 'companion-stratege-fenetre-dordre', 'skill' => 'fenetre-dordre', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => []],
                    ['slug' => 'companion-stratege-plan-decisionnel', 'skill' => 'plan-decisionnel', 'column' => 2, 'row' => 1, 'cost' => 2, 'special_cost' => 1, 'required_level' => 5, 'prerequisites' => ['companion-stratege-fenetre-dordre']],
                ],
            ],
            [
                'slug' => 'companion-observateur-sightline',
                'name' => 'Ligne de Mire',
                'description' => 'Renforce la spécialisation distance de l’Observateur.',
                'icon' => 'target',
                'subject_type' => 'companion',
                'subject_key' => 'observateur',
                'class_slug' => 'observer',
                'role_slug' => 'dps',
                'specialization_slug' => 'shooter',
                'nodes' => [
                    ['slug' => 'companion-observateur-percee-balistique', 'skill' => 'percee-balistique', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => []],
                    ['slug' => 'companion-observateur-salve-interception', 'skill' => 'salve-dinterception', 'column' => 2, 'row' => 1, 'cost' => 2, 'special_cost' => 1, 'required_level' => 5, 'prerequisites' => ['companion-observateur-percee-balistique']],
                ],
            ],
            [
                'slug' => 'companion-eclaireur-route',
                'name' => 'Route de l’Éclaireur',
                'description' => 'Accentue la mobilité et la pression mêlée du scout.',
                'icon' => 'sparkles',
                'subject_type' => 'companion',
                'subject_key' => 'eclaireur',
                'class_slug' => 'observer',
                'role_slug' => 'hybrid',
                'specialization_slug' => 'scout',
                'nodes' => [
                    ['slug' => 'companion-eclaireur-piste-chaude', 'skill' => 'piste-chaude', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => []],
                    ['slug' => 'companion-eclaireur-coupure-trajectoire', 'skill' => 'coupure-de-trajectoire', 'column' => 2, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 5, 'prerequisites' => ['companion-eclaireur-piste-chaude']],
                ],
            ],
            [
                'slug' => 'companion-gardien-bastion',
                'name' => 'Bastion du Gardien',
                'description' => 'Donne plus de carburant au tank et à ses boucliers.',
                'icon' => 'shield',
                'subject_type' => 'companion',
                'subject_key' => 'gardien',
                'class_slug' => 'guardian',
                'role_slug' => 'tank',
                'specialization_slug' => 'protector',
                'nodes' => [
                    ['slug' => 'companion-gardien-garde-partagee', 'skill' => 'garde-partagee', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => []],
                    ['slug' => 'companion-gardien-bastion-tournant', 'skill' => 'bastion-tournant', 'column' => 2, 'row' => 1, 'cost' => 2, 'special_cost' => 1, 'required_level' => 5, 'prerequisites' => ['companion-gardien-garde-partagee']],
                ],
            ],
            [
                'slug' => 'companion-analyste-grid',
                'name' => 'Grille de l’Analyste',
                'description' => 'Pousse le contrôle magique et les builds mentaux du compagnon analyste.',
                'icon' => 'mind',
                'subject_type' => 'companion',
                'subject_key' => 'analyste',
                'class_slug' => 'strategist',
                'role_slug' => 'hybrid',
                'specialization_slug' => 'analyst',
                'nodes' => [
                    ['slug' => 'companion-analyste-cartographie-risque', 'skill' => 'cartographie-du-risque', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 3, 'prerequisites' => []],
                    ['slug' => 'companion-analyste-onde-clarte', 'skill' => 'onde-de-clarte', 'column' => 2, 'row' => 1, 'cost' => 2, 'special_cost' => 1, 'required_level' => 5, 'prerequisites' => ['companion-analyste-cartographie-risque']],
                ],
            ],
            [
                'slug' => 'companion-polyvalent-adapt',
                'name' => 'Matrice du Polyvalent',
                'description' => 'Verrouille le style hybride du compagnon polyvalent.',
                'icon' => 'burst',
                'subject_type' => 'companion',
                'subject_key' => 'polyvalent',
                'class_slug' => 'guardian',
                'role_slug' => 'hybrid',
                'specialization_slug' => 'counter',
                'nodes' => [
                    ['slug' => 'companion-polyvalent-surcadence', 'skill' => 'surcadence', 'column' => 1, 'row' => 1, 'cost' => 1, 'special_cost' => 0, 'required_level' => 4, 'prerequisites' => []],
                    ['slug' => 'companion-polyvalent-rupture-adaptative', 'skill' => 'rupture-adaptative', 'column' => 2, 'row' => 1, 'cost' => 2, 'special_cost' => 1, 'required_level' => 6, 'prerequisites' => ['companion-polyvalent-surcadence']],
                ],
            ],
        ];
    }

    protected function animationKey(array $skillData): string
    {
        if (($skillData['slot_type'] ?? 'active') === 'passive') {
            return 'idle';
        }

        return match ($skillData['type']) {
            SkillType::Heal, SkillType::Buff, SkillType::ThemeBonus => 'cast',
            SkillType::Shield, SkillType::Defense, SkillType::PenaltyReduction => 'guard',
            SkillType::AreaAttack => 'slash',
            SkillType::Debuff => 'cast',
            default => (($skillData['range_type'] ?? null) === 'ranged' ? 'shoot' : 'attack'),
        };
    }
}
